# Dependencies
markdown:         kramdown
kramdown:
  parse_block_html: true 
highlighter:      rouge

# Permalinks
permalink:  /:categories/:year/:month/:day/:title
paginate_path:  /AWRA_GIS_R_Workshop/page:num

# Setup
title:            'R Spatial Workshop for 2018 AWRA GIS Conference'
tagline:          ''
description:      'This material is for a workshop at the 2018 AWRA GIS
                  conference in Orlando, FL, April 2018.'
url:              http://mhweber.github.io/AWRA_GIS_R_Workshop
baseurl:          /AWRA_GIS_R_Workshop

author:
  name:           'Marc Weber'
  url:            http://mhweber.github.io

paginate:         15

timezone:         America/Los_Angeles

#Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap


# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

auto: true # automatically update your jekyll
server: true # runs a local server
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

